import Head from "next/head";
import dynamic from "next/dynamic";
import { useEffect, useState, useRef } from "react";
const Header = dynamic(() => import("../components/Header"));
const Result = dynamic(() => import("../components/Result"));
import { useDispatch, useSelector } from "react-redux";
import { addMovie } from "../features/movieSlice";
import { resetGrid } from "../features/gridSlice";
import Reveal from "react-reveal/Reveal";
import SortingHeader from "../components/SortingHeader";
import { pageCount } from "../utils/helpers";
import PaginationNew from "../components/PaginationNew";
import { useRouter } from "next/router";
import { show_per_page } from "../config";

export default function Allmovie({ movie, totalMovieCount }) {
  console.log(movie);
  const router = useRouter();
  const movies = movie;
  const dispatch = useDispatch();
  const [loading, setLoading] = useState(true);
  const [currentpage, setCurrentPage] = useState(1);
  const [postsPerPage] = useState(12);
  const [sortingCriteria, setSortingCriteria] = useState("releasedateDsc");

  const [sortingMovie, setSortingMovie] = useState(
    movies
      .slice()
      .sort(
        (b, a) =>
          new Date(a?.releasedate).getTime() -
          new Date(b?.releasedate).getTime()
      )
  );

  useEffect(() => {
    if (sortingCriteria === "releasedateDsc") {
      let newMovie = movies
        .slice()
        .sort(
          (b, a) =>
            new Date(a?.releasedate).getTime() -
            new Date(b?.releasedate).getTime()
        );
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "releasedateAsc") {
      let newMovie = movies
        .slice()
        .sort(
          (b, a) =>
            new Date(b?.releasedate).getTime() -
            new Date(a?.releasedate).getTime()
        );
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "idAsc") {
      let newMovie = movies.slice().sort(function (a, b) {
        return a.id.localeCompare(b.id);
      });
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "idDsc") {
      let newMovie = movies.slice().sort(function (b, a) {
        return a.id.localeCompare(b.id);
      });
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "titleAsc") {
      let newMovie = movies.slice().sort(function (a, b) {
        return a.actor.localeCompare(b.actor);
      });
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "titleDsc") {
      let newMovie = movies.slice().sort(function (b, a) {
        return a.actor.localeCompare(b.actor);
      });
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "ratingDsc") {
      let newMovie = movies.slice().sort(function (a, b) {
        return Number(b.rating) - Number(a.rating);
      });
      setSortingMovie(newMovie);
    }
    if (sortingCriteria === "ratingAsc") {
      let newMovie = movies.slice().sort(function (a, b) {
        return Number(a.rating) - Number(b.rating);
      });
      setSortingMovie(newMovie);
    }
  }, [movies, sortingCriteria]);

  const indexOfLastPost = currentpage * postsPerPage;
  const indexOfFirstPost = indexOfLastPost - postsPerPage;
  const currentMovie = sortingMovie?.slice(indexOfFirstPost, indexOfLastPost);

  useEffect(() => {
    dispatch(resetGrid());
    dispatch(addMovie(movies));
    setLoading(false);
  }, [movies]);

  return (
    <div className="">
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header collections={movies} />
      <SortingHeader setSortingCriteria={setSortingCriteria} />

      <main className="mx-auto max-w-screen">
        <Reveal effect="fadeInUp">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <Result collections={movie} allDataisTrue />
          )}
        </Reveal>
        <PaginationNew totalMovieCount={totalMovieCount} />
      </main>
    </div>
  );
}
export async function getServerSideProps({ req, res }) {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );
  const movieRes = await fetch(
    "https://raw.githubusercontent.com/zonghongdevelop3/javdb.io/main/data/allmovie.json"
  );
  const data = await movieRes.json();
  // count how many pages
  let totalMovieCount = pageCount(data.length);
  const sortMovie = data
    .slice()
    .sort(
      (b, a) =>
        new Date(a?.releasedate).getTime() - new Date(b?.releasedate).getTime()
    );
  let totalMovie = sortMovie.slice(0, show_per_page);

  return {
    props: { movie: totalMovie, totalMovieCount },
  };
}
