import { useRouter } from "next/router";
import Head from "next/head";
import HeaderItems from "../components/HeaderItems";
import { useState } from "react";
import {
  AdjustmentsIcon,
  FireIcon,
  GlobeAltIcon,
  HomeIcon,
  SearchIcon,
  GiftIcon,
} from "@heroicons/react/outline";
import BannerItem from "../components/BannerItem";
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";

function Mobilerandom({ movies }) {
  const router = useRouter();
  const [number, setNumber] = useState("");
  const [active1, setActive1] = useState(false);
  const [active3, setActive3] = useState(false);
  const [active5, setActive5] = useState(false);
  const [active10, setActive10] = useState(true);
  const [active20, setActive20] = useState(false);
  const [active30, setActive30] = useState(false);
  const [active50, setActive50] = useState(false);

  const navtoHome = () => {
    router.push("/");
  };

  const navtosearch = () => {
    router.push("/search");
  };

  const navtofilter = () => {
    router.push("/filter");
  };

  const navtowebsite = () => {
    router.push("/website");
  };

  const navtoRank = () => {
    router.push("/actress");
  };
  const navtomobileRandom = () => {
    router.push("/mobilerandom");
  };
  const handleChange = (value) => {
    setSearchTerm(value);
    filterData(value);
  };
  const navtoRandom = () => {
    router.push("/random");
  };

  const shuffle1 = () => {
    setNumber(1);
    setActive1(true);
    setActive3(false);
    setActive5(false);
    setActive10(false);
    setActive20(false);
    setActive50(false);
  };

  const shuffle3 = () => {
    setNumber(3);
    setActive1(false);
    setActive3(true);
    setActive5(false);
    setActive10(false);
    setActive20(false);
    setActive50(false);
  };
  const shuffle5 = () => {
    setNumber(5);
    setActive1(false);
    setActive3(false);
    setActive5(true);
    setActive10(false);
    setActive20(false);
    setActive50(false);
  };
  const shuffle10 = () => {
    setNumber(10);
    setActive1(false);
    setActive3(false);
    setActive5(false);
    setActive10(true);
    setActive20(false);
    setActive50(false);
  };

  const shuffle20 = () => {
    setNumber(20);
    setActive1(false);
    setActive3(false);
    setActive5(false);
    setActive10(false);
    setActive20(true);
    setActive50(false);
  };
  const shuffle30 = () => {
    setNumber(30);
    setActive1(false);
    setActive3(false);
    setActive5(false);
    setActive10(false);
    setActive20(false);
    setActive30(true);
    setActive50(false);
  };

  const shuffle50 = () => {
    setNumber(50);
    setActive1(false);
    setActive3(false);
    setActive5(false);
    setActive10(false);
    setActive20(false);
    setActive50(true);
  };
  return (
    <div>
      <Head>
        <title>My JavLib || Random</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center sticky top-0 z-50 h-auto m-5">
        <div className="flex items-center space-x-6">
          <div className="flex flex-grow justify-evenly max-w-2xl">
            <HeaderItems title="HOME" Icon={HomeIcon} navtoHome={navtoHome} />
            <HeaderItems
              title="FILTER"
              Icon={AdjustmentsIcon}
              navtosearch={navtofilter}
            />
            <HeaderItems
              title="SEARCH"
              Icon={SearchIcon}
              navtosearch={navtosearch}
            />
            <HeaderItems
              title="WEBSITE"
              Icon={GlobeAltIcon}
              navtosearch={navtowebsite}
            />
            <HeaderItems
              title="ACTRESS"
              Icon={FireIcon}
              navtosearch={navtoRank}
            />
            <div className="flex lg:hidden">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtomobileRandom}
              />
            </div>
            <div className="hidden lg:flex">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtoRandom}
              />
            </div>
          </div>
        </div>

        <div className="w-full px-10 whitespace-nowrap flex items-center justify-center space-x-10 cursor-pointer overflow-x-scroll scrollbar-hide">
          <div className="pl-10" />
          <div
            onClick={shuffle1}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active1 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>1</h1>
          </div>
          <div
            onClick={shuffle3}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active3 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>3</h1>
          </div>
          <div
            onClick={shuffle5}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active5 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>5</h1>
          </div>
          <div
            onClick={shuffle10}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active10 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>10</h1>
          </div>
          <div
            onClick={shuffle20}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active20 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>20</h1>
          </div>
          <div
            onClick={shuffle30}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active30 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>30</h1>
          </div>
          <div
            onClick={shuffle50}
            className={`p-2 flex items-center justify-center font-bold tracking-widest  w-8 h-8 bg-gradient-to-l text-white-800 ${
              active50 && "bg-white from-[#06202A]"
            }`}
          >
            <h1>50</h1>
          </div>
        </div>
      </div>
      <div className="h-screen">
        <Carousel
          autoPlay
          infiniteLoop
          showStatus={false}
          showIndicators={false}
          showThumbs={false}
          interval={5000}
        >
          {movies.slice(movies, number).map((collection) => (
            <div key={index} className=" cursor-pointer">
              <BannerItem
                id={collection?.id}
                code={collection?.id}
                image={collection?.bigimageurl}
                extraimageurl={collection?.extraimageurl}
                name={collection?.actor}
                title={collection?.title}
                genre={collection?.genre}
                publisher={collection?.studio}
                series={collection?.tag}
                filePath={collection?.filePath}
                sourceurl={collection?.sourceurl}
                studio={collection?.studio}
              />
            </div>
          ))}
        </Carousel>
      </div>
    </div>
  );
}

export default Mobilerandom;
export const getServerSideProps = async ({ req, res }) => {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );
  const movieRes = await fetch(
    "https://raw.githubusercontent.com/zonghongdevelop3/javdb.io/main/data/movie.json"
  );
  const data = await movieRes.json();
  const sortMovie = data
    .slice()
    .sort(
      (b, a) =>
        new Date(a?.releasedate).getTime() - new Date(b?.releasedate).getTime()
    );
  return {
    props: {
      movies: sortMovie?.sort(() => 0.5 - Math.random()),
    },
  };
};
