import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import HeaderItems from "../components/HeaderItems";

import {
  AdjustmentsIcon,
  FireIcon,
  GlobeAltIcon,
  HomeIcon,
  SearchIcon,
  GiftIcon,
  SearchCircleIcon,
  HeartIcon,
  SparklesIcon,
} from "@heroicons/react/outline";

function Searchall() {
  const router = useRouter();
  const [isSearch, setIsSearch] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  const navtoHome = () => {
    router.push("/");
  };

  const navtosearch = () => {
    router.push("/search");
  };
  const navtoSearchAll = () => {
    router.push("/searchall");
  };
  const navtoAll = () => {
    router.push("/allmovies");
  };

  const navtofilter = () => {
    router.push("/filter");
  };

  const navtowebsite = () => {
    router.push("/website");
  };

  const navtoRank = () => {
    router.push("/actress");
  };
  const navtomobileRandom = () => {
    router.push("/mobilerandom");
  };
  const handleChange = (value) => {
    setSearchTerm(value);
    filterData(value);
  };
  const navtoRandom = () => {
    router.push("/random");
  };

  const filterData = (value) => {
    setIsSearch(true);
    const Value = value.toLocaleUpperCase().trim();
    if (Value === "") setSearchResults(dataList);
    else {
      const filteredData = dataList?.filter((item) => {
        return Object?.keys(item)?.some((key) =>
          excludeColumns.includes(key)
            ? false
            : item[key]?.toString().toLocaleUpperCase().includes(Value)
        );
      });

      setSearchResults(filteredData);
    }
  };

  const searchMe = (e) => {
    e.preventDefault();
    router.push(`/searchfilter/${searchTerm}`);
  };

  return (
    <div>
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center sticky top-0 z-50 h-auto m-5">
        <div className="flex items-center space-x-6">
          <div className="flex flex-grow justify-evenly max-w-2xl">
            <HeaderItems title="HOME" Icon={HomeIcon} navtoHome={navtoHome} />
            <HeaderItems title="ALL" Icon={SparklesIcon} navtoHome={navtoAll} />
            <HeaderItems
              title="SEARCH ALL"
              Icon={HeartIcon}
              navtosearch={navtoSearchAll}
            />
            <HeaderItems
              title="FILTER"
              Icon={AdjustmentsIcon}
              navtosearch={navtofilter}
            />
            <HeaderItems
              title="SEARCH"
              Icon={SearchIcon}
              navtosearch={navtosearch}
            />
            <HeaderItems
              title="WEBSITE"
              Icon={GlobeAltIcon}
              navtosearch={navtowebsite}
            />
            <HeaderItems
              title="ACTRESS"
              Icon={FireIcon}
              navtosearch={navtoRank}
            />
            <div className="flex lg:hidden">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtomobileRandom}
              />
            </div>
            <div className="hidden lg:flex">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtoRandom}
              />
            </div>
          </div>
        </div>

        <div className="w-full flex items-center cursor-pointer">
          <form
            onSubmit={searchMe}
            className="w-full flex items-center cursor-pointer"
          >
            <input
              className={` focus:shadow-2xl focus:shadow-blue-500 font-bold tracking-widest bg-gradient-to-l text-gray-800 from-[#06202A] p-2 px-5 h-full w-full flex-grow rounded flex-shrink rounded-l-md focus:outline-none
           `}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by Movie"
            />
            <SearchCircleIcon
              className="w-8 h-8 hover:text-cyan-500 cursor-pointer"
              onClick={searchMe}
            />
          </form>
        </div>
      </div>

      <main className="mx-auto max-w-screen"></main>
    </div>
  );
}

export default Searchall;
