import { useState } from "react";
import dynamic from "next/dynamic";
const HeaderItems = dynamic(() => import("../../components/HeaderItems"));
const ResultList = dynamic(() => import("../../components/ResultList"));
const PaginationNew = dynamic(() => import("../../components/PaginationNew"));
import { useRouter } from "next/router";
import Head from "next/head";
import {
  AdjustmentsIcon,
  FireIcon,
  GlobeAltIcon,
  HomeIcon,
  SearchIcon,
  GiftIcon,
  SearchCircleIcon,
  SparklesIcon,
  HeartIcon,
} from "@heroicons/react/outline";
import { fetchAllMovies, fetchSearchMovies } from "../../utils/fetchmovies";

function SearchFilter({ moviesData, totalMovieCount, totalMoviesResult }) {
  const movies = JSON.parse(moviesData);
  const router = useRouter();
  const currentParam = router.query.filter;
  const [searchTerm, setSearchTerm] = useState("");

  const navtoHome = () => {
    router.push("/");
  };

  const navtosearch = () => {
    router.push("/search");
  };

  const navtofilter = () => {
    router.push("/filter");
  };

  const navtowebsite = () => {
    router.push("/website");
  };

  const navtoRank = () => {
    router.push("/actress");
  };
  const navtomobileRandom = () => {
    router.push("/mobilerandom");
  };

  const navtoRandom = () => {
    router.push("/random");
  };
  const searchMe = (e) => {
    e.preventDefault();
    router.push(`/searchfilter/${searchTerm}`);
  };
  const navtoAll = () => {
    router.push("/allmovies");
  };
  const navtoSearchAll = () => {
    router.push("/searchall");
  };

  return (
    <div>
      <Head>
        <title>My JavLib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center sticky top-0 z-50 h-auto m-5">
        <div className="flex items-center space-x-6">
          <div className="flex flex-grow justify-evenly max-w-2xl">
            <HeaderItems title="HOME" Icon={HomeIcon} navtoHome={navtoHome} />
            <HeaderItems title="ALL" Icon={SparklesIcon} navtoHome={navtoAll} />
            <HeaderItems
              title="SEARCH ALL"
              Icon={HeartIcon}
              navtosearch={navtoSearchAll}
            />
            <HeaderItems
              title="FILTER"
              Icon={AdjustmentsIcon}
              navtosearch={navtofilter}
            />
            <HeaderItems
              title="SEARCH"
              Icon={SearchIcon}
              navtosearch={navtosearch}
            />
            <HeaderItems
              title="WEBSITE"
              Icon={GlobeAltIcon}
              navtosearch={navtowebsite}
            />
            <HeaderItems
              title="ACTRESS"
              Icon={FireIcon}
              navtosearch={navtoRank}
            />
            <div className="flex lg:hidden">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtomobileRandom}
              />
            </div>
            <div className="hidden lg:flex">
              <HeaderItems
                title="Random"
                Icon={GiftIcon}
                navtosearch={navtoRandom}
              />
            </div>
          </div>
        </div>
        <div className="w-full flex items-center cursor-pointer">
          <form
            onSubmit={searchMe}
            className="w-full flex items-center cursor-pointer"
          >
            <input
              className={` focus:shadow-2xl focus:shadow-blue-500 font-bold tracking-widest bg-gradient-to-l text-gray-800 from-[#06202A] p-2 px-5 h-full w-full flex-grow rounded flex-shrink rounded-l-md focus:outline-none
           `}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by Movie"
            />
            <SearchCircleIcon
              className="w-8 h-8 hover:text-cyan-500 cursor-pointer"
              onClick={searchMe}
            />
          </form>
        </div>
      </div>

      <main className="mx-auto max-w-screen">
        {totalMoviesResult > 0 && (
          <h1 className=" text-white text-xl lg:text-3xl mt-10 font-light text-center">
            {totalMoviesResult} movies
          </h1>
        )}

        <div className="px-5 my-10 grid grid-flow-row-dense md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {movies?.map((collection) => (
            <ResultList
              key={collection?.id}
              id={collection?.id}
              code={collection?.id}
              image={collection?.bigimageurl}
              extraimageurl={collection?.extraimageurl}
              name={collection?.actor}
              title={collection?.title}
              genre={collection?.genre}
              publisher={collection?.studio}
              series={collection?.tag}
              filePath={collection?.filePath}
              sourceurl={collection?.sourceurl}
              studio={collection?.studio}
              releasedate={collection?.releasedate}
            />
          ))}
        </div>

        {totalMovieCount === 0 && (
          <div className="flex items-center justify-center cursor-pointer">
            <h1 className="text-6xl text-gray-400 text-center font-medium tracking-widest">
              No Movies found
            </h1>
          </div>
        )}
        <PaginationNew
          totalMovieCount={totalMovieCount}
          search
          currentParam={currentParam}
        />
      </main>
    </div>
  );
}

export default SearchFilter;
export async function getStaticPaths() {
  const data = await fetchAllMovies();
  const moviesCount = data.totalMovieCount;
  // totalMovieCount number convert into a array
  let pageIntoArray = Array.from(Array(moviesCount).keys());

  let paths = [];

  pageIntoArray.map((path) =>
    paths.push({
      params: { filter: `${path}` },
    })
  );

  return {
    paths,
    fallback: "blocking",
  };
}

export async function getStaticProps({ params }) {
  const value = params.filter;

  const data = await fetchSearchMovies(value);
  const totalMovie = data.movies;
  const totalMoviesResult = data.totalMoviesResult;
  const totalMovieCount = data.totalMovieCount;

  return {
    props: {
      moviesData: JSON.stringify(totalMovie),

      totalMoviesResult,
      totalMovieCount,
    },
  };
}
